name: CSC307 Learning React CI

on:
  push:
    branches: [test-gh-actions]
  # branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # fix working directory
      - run: npm ci
        working-directory: ./react-assignment1
      - run: npm run build --if-present
        working-directory: ./react-assignment1
      - run: npm test
        working-directory: ./react-assignment1
